### ISSUE TITLE
Breaks on simple markdown

### ISSUE THREAD

**Issue by bootstraponline** [leeoniya/reMarked.js#10]
Attempting to convert [example.md](https://raw.github.com/bootstraponline/livepreview/gh-pages/example.md) produces many JavaScript errors. I've tried patching the library a bit, however it just uncovers more problems.

``` javascript
    function nodeName(e) {
// .nodeName can be undefined and with out this check nodeName breaks
    if (e.nodeName == undefined)
      return '';
```

``` javascript
    initK: function()
        {
            var i;
            if (this.e.hasChildNodes()) {  // has no method 'hasChildNodes'
```

**Comment by leeoniya** [comment]
Perhaps you are confused what this library is designed to do - it converts an existing DOM structure _into_ markdown, not the other way around. If you want to convert markdown into DOM, you should look at another lib, like https://github.com/chjj/marked/

**Comment by bootstraponline** [comment]
Thanks for your response. I was passing in a string of HTML to [convert to markdown](http://bootstraponline.github.com/livepreview_wysi/public/) instead of a DOM element.

**Comment by leeoniya** [comment]
This gave me a good idea, I should allow an html-string to be passed into reMarked.js and set that as the `innerHtml` of a dummy `div` to quickly parse it and produce the same markdown output. Low effort, high reward. Maybe a 3-liner patch tonight :D

**Comment by bootstraponline** [comment]
That'd be amazing.

**Comment by bootstraponline** [comment]
I tested out [the change](https://github.com/bootstraponline/livepreview_wysi/commit/486f58b0f0790d77df1bfa2c64900b9074487586) and it's so much better than what I was using before. The code examples now translate properly.

The only missing feature is GitHub Flavored Markdown tables as seen in [example.md](https://raw.github.com/bootstraponline/livepreview/gh-pages/example.md).
- [demo](http://bootstraponline.github.com/livepreview_wysi/public/) of HTML to md conversion using reMarked.

**Comment by leeoniya** [comment]
interesting. i haven't touched this project for a few months and they must have added a few more GFM features, including tables and some other stuff that wasn't there before:
https://raw.github.com/suan/github-flavored-markdown-test/master/README.md

i was using this one for testing/reference previously:
https://raw.github.com/mojombo/github-flavored-markdown/gh-pages/_site/sample_content.md
http://github.github.com/github-flavored-markdown/sample_content.html

the tables look pretty quick to implement, i'll add them over the weekend.

**Comment by bootstraponline** [comment]
One aspect of tables that's not in those links is [omitting leading pipes](https://github.com/bootstraponline/js_markdown_tables/blob/master/test_pagedown.html#L13).

**Comment by leeoniya** [comment]
cool, thanks. do you have a link to the actual spec for this, or some official test markdown and output html samples? please link them under issue #12

**Comment by bootstraponline** [comment]
The spec is from [PHP Markdown Extra](http://michelf.com/projects/php-markdown/extra/#table). I've added a link to #12.
