### ISSUE TITLE
bold missing?

### ISSUE THREAD

**Issue by bootstraponline** [leeoniya/reMarked.js#17]
`<b>bold</b>` becomes `bold`
- [reMarked + bootstrap wysihtml5](http://bootstraponline.github.com/livepreview_wysi/public/)

**Comment by leeoniya** [comment]
you might also want to update your `livepreview.js` with the recently added options https://github.com/leeoniya/reMarked.js/blob/master/README.md

on the other hand, you only need to pass in those opts for which you want to change the default settings. if you're not changing the defaults, there is no need to pass in any options at all.

**Comment by bootstraponline** [comment]
Thanks! I'm just using the defaults for now so that's good to know the options object isn't required.

I think the indentation on 239b73a is slightly off.

**Comment by leeoniya** [comment]
it's intentional since they just inherit from the lines above them.
