### ISSUE TITLE
allow user input in demo page

### ISSUE THREAD

**Issue by sunaku** [leeoniya/reMarked.js#23]
Hello,

Please enhance [the demo page](http://leeoniya.github.com/reMarked.js/) to allow the user to:
1. Enter their input HTML in a textarea
2. Press the "reMark it!" button
3. See the resulting Markdown output

This would allow people to use reMarked.js without having to install it!

Thanks for your consideration.

**Comment by leeoniya** [comment]
yeah, it's been on my todo list for a while. also maybe a config sidebar for toggling different options. i'll try to get it done in the next few days...

**Comment by leeoniya** [comment]
done, try it out.

**Comment by sunaku** [comment]
Thanks, it works but there is a styling problem:  if the browser window is not wide enough, then the textarea obscures the "reMark it" button.  That is, I'm able to input my custom HTML but I cannot click on the button (it's _behind_ the textarea) to convert it into markdown. :sweat_smile:

**Comment by sunaku** [comment]
Here is a simple (but not _pretty_) fix:

``` diff
diff --git a/css/demo.css b/css/demo.css
index 991dc1d..e01834a 100644
--- a/css/demo.css
+++ b/css/demo.css
@@ -3,7 +3,7 @@
 }

 .markdown-body,
-#remarked {
+#remarked, #html-inp {
        margin-left: 230px;
 }

@@ -59,11 +59,5 @@
 #html-inp {
        width: 960px;
        height: 500px;
-       position: fixed;
-       top: 50%;
-       left: 50%;
-       margin-top: -250px;
-       margin-left: -480px;
-       padding: 5px;
        display: none;
```

**Comment by leeoniya** [comment]
all fixed up

**Comment by sunaku** [comment]
Awesome! Thanks :smiley_cat:
