### ISSUE TITLE
loss of essential whitespace

### ISSUE THREAD

**Issue by alpinegizmo** [leeoniya/reMarked.js#24]
```
reMarker.render('<b>a</b> <i>b</i>')
"**a**_b_"
```

Note that the space between them is lost.

**Comment by leeoniya** [comment]
hmm, that's no good at all. off the top of my head, nothing obvious. at first i thought i missed an inline element in the regex that prevents this, but both `b` and `i` are there: https://github.com/leeoniya/reMarked.js/blob/master/reMarked.js#L150

i'll look into this soon, thanks for reporting.
