### ISSUE TITLE
&nbsp; characters not treated as whitespace

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/reMarked.js#34]
followup to #32.

@andrewliang

**Comment by leeoniya** [comment]
i'm not convinced `&nbsp;` should be treated as whitepace or even decoded to another escape sequence. markdown supports html within it. pretty sure any special entities should stay the way they are.

**Comment by ghost** [comment]
Yes you're right. After doing a few unit tests, I realize I made a mistake and I totally agree. I'm still kind of new to markdown. :)

**Comment by leeoniya** [comment]
there's now an option for converting `&nbsp;`s to regular spaces. see readme.
