### ISSUE TITLE
Respect Loose Lists

### ISSUE THREAD

**Issue by wbw20** [leeoniya/reMarked.js#41]
As mentioned in [the original spec](http://daringfireball.net/projects/markdown/syntax#list)

``` html
<p>Asterisks loose:</p>

<ul>
  <li><p>asterisk 1</p></li>
  <li><p>asterisk 2</p></li>
  <li><p>asterisk 3</p></li>
</ul>
```

should render as:

``` md
Asterisks loose:

*   asterisk 1

*   asterisk 2

*   asterisk 3
```

but instead renders as:

``` md
Asterisks loose:

* asterisk 1
* asterisk 2
* asterisk 3
```

These are called loose lists and many common markdown renderers support them.  Might be something to consider adding support for.

**Comment by leeoniya** [comment]
done, try it out.
